name: CI to Docker Hub
on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Main Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR.ACCESS_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          tag: ${{ github.event.release.tag_name }}
          push: true

      - name: Build and Push Nginx Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR.ACCESS_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}-nginx
          tag: ${{ github.event.release.tag_name }}
          push: true
